# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622815dd1829ac6f650b2455bcf0c45e14c7b86d45e0a6a4b1f43a7433a39526d94f458f2f37f63f73da6771432e62dd025db932c20cab12f097b23a6207f3a5

test:
  secret_key_base: b954f5b94ff7150c71c5f1c6ba36469f243a7415e0d35a60ede3f7f924a1c424449057aaad90351cfc1d95ceb2c1b1088526871b52765b97f429eda92236ef42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
